# Generated by Django 4.1.3 on 2023-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_path',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
