# Generated by Django 4.1.3 on 2023-05-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dish_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('quantities', models.JSONField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
