# Generated by Django 4.1.3 on 2023-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(default='Default'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Default', max_length=400),
        ),
    ]
