# Generated by Django 4.1.3 on 2023-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Закуски'), ('main', 'Основні страви'), ('cheese', 'Сири'), ('dessert', 'Десерти'), ('beverages', 'Напої')], default='main', max_length=200),
            preserve_default=False,
        ),
    ]
